account/urls.py
from django.contrib import admin
from django.urls import path
from account import views


app_name="account"

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name="home"),

    # path('createacc',views.createacc,name="createacc"),
    #
    # path('detail/<int:n>',views.detail,name="detail"),

    path('reg/',views.register,name="register"),

    path('log/',views.user_login,name="login"),

    path('logout/', views.user_logout, name="user_logout"),

    path('viewtransaction/', views.viewtransaction, name="viewtransaction"),

    path('create/', views.create, name="create"),

    path('update/', views.update, name="update"),

    path('edit/<int:n>', views.edit, name="edit"),

    path('delete/<int:n>', views.delete, name="delete"),

]

bank_account_management/urls.py
from django.contrib import admin
from django.urls import path,include
from account import views
# from django.conf import settings             # these two path must import for settings.DEBUG (media content view)
# from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('',include('account.urls')),


]

# if settings.DEBUG:                                          #for viewing content inside media in website add this settings.DEBUG
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Account(models.Model):
    account_number = models.TextField(max_length=20, unique=True)
    account_holder_name = models.CharField(max_length=100)
    account_type = models.CharField(max_length=50)
    balance = models.DecimalField(max_digits=10, decimal_places=2)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.account_holder_name



class Transaction(models.Model):
    # TRANSACTION_TYPES = (
    #     ('deposit', 'Deposit'),
    #     ('withdrawal', 'Withdrawal'),
    # )

    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    transaction_type = models.CharField(max_length=20)                 # , choices=TRANSACTION_TYPES
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateTimeField(auto_now_add=True)
    description = models.TextField(blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

        # return f"{self.transaction_type} of {self.amount} on {self.date}"

account/forms.py
from django import forms
from account.models import Account
from django import forms


class Accountform(forms.ModelForm):
    class Meta:
        model=Account
        fields="__all__"

      ##  or

        # fields=['title','author']   # or we can give our desired field so that it doesnt takes all fields

      ## or

        # exclude=['price']   # not taking price field and rest all field taking

account/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from account.forms import Accountform
from account.models import Account,Transaction


# Create your views here.


def home(request):
    return render(request,'home.html')


def register(request):                                           #here context dictionary type used to send data from view to html
    if (request.method == "POST"):  # after submission this condition works
        ##normal field
        u = request.POST["u"]  # for normal data request.POST for taking value
        p = request.POST["p"]
        cp = request.POST["cp"]
        e = request.POST["e"]
        fn = request.POST["fn"]
        ln = request.POST["ln"]
        if(cp==p):
            u=User.objects.create_user(username=u,password=p,email=e,first_name=fn,last_name=ln)
            u.save()
            return redirect('account:home')
        else:
            return HttpResponse("passwords are not same")
    return render(request, 'register.html')


def user_login(request):
    if (request.method == "POST"):
        u = request.POST["u"]
        p = request.POST["p"]
        user=authenticate(username=u,password=p)
        if(user):
            login(request,user)
            return redirect('account:home')
        else:
            return HttpResponse("invalid credentials")

    return render(request,'login.html')


def user_logout(request):
    logout(request)               #here logout(rquest) is builtin func so need to import and just add this
    # return user_login(request)
    return redirect('account:home')




def viewtransaction(request):
    u=request.user
    t = Transaction.objects.filter(user=u)
    return render(request, "viewtransaction.html", {"t": t})


def create(request):
    if (request.method == "POST"):  # after submission this condition works
        u = request.user

        ##normal field
        t = request.POST["an"]  # for normal data request.POST for taking value
        a = request.POST["hn"]
        p = request.POST["at"]


        cv = request.POST["b"]  # for file field  request.FILES for taking value

        a = Account.objects.create(account_number=t, account_holder_name=a, account_type=p, balance=cv,user=u)

        a.save()
        return home(request)
    return render(request, 'create.html')


def update(request):
    u=request.user
    a=Account.objects.filter(user=u)
    return render(request, 'update2.html',{'a':a})

def edit(request,n):
    a=Account.objects.get(pk=n)    #first we fetch that particular field with id ( arguement passed from view.html
    if (request.method == "POST"):  # after submission this condition works
        form = Accountform(request.POST,instance=a)
                      #here request.post is for normal field and .FILE is for media content    #instance=b is that id with field datas
        if form.is_valid():  # checks the validity of form, its a django in built func
                form.save()     #saves or insert the values entered in form field to their apropriate table field coz the form already created based on table
                return home(request)

    form = Accountform(instance=a)                 #need to create an empty form here to display in add1.html
                #here instance =b is given in empty form to fill the data in form field when form loads then edit process up

    return render(request, 'update.html',{'form':form})



def delete(request,n):
    a=Account.objects.get(id=n)    #for delete first we fetch that particular field with id ( arguement passed from view.html)
    a.delete()               #then .delete()
    return home(request)   #optional can direct to another page after deleting or any process

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
  <title>{% block title%}base{% endblock %}</title>        <!--here block title is used to get different title in different pages,this just declared here and content is declared inside other template using this syntax-->

 <link rel="stylesheet" href="{% static 'css/style.css' %}">

                            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <style>
        a
        {
        color:red;
        }
    </style>
</head>
<body>


<!--                                 using template inheritance                                                   -->

<nav class="navbar navbar-expand-lg navbar-danger bg-white">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">SOOHAN BANK</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="position:relative;">

          <!--    links added here -->              <!-- links added into nav links  -->
        <li class="nav-item">
          <a class="nav-link active ps-5" aria-current="page" href="{% url 'account:home' %}">Home</a>
        </li>

          {% if user.is_authenticated %}
          <li class="nav-item">
          <a class="nav-link ps-5" href="{% url 'account:create' %}">Create Account</a>
        </li>
          <li class="nav-item">
          <a class="nav-link ps-5" href="{% url 'account:viewtransaction' %}">View Transactions</a>
        </li>
         <li class="nav-item">
          <a class="nav-link ps-5" href="{% url 'account:update' %}">Update Account</a>
        </li>
<!--         <li class="nav-item">-->
<!--          <a class="nav-link ps-5" href="">Delete Account</a>-->
<!--        </li>-->
        <li class="nav-item" style="position:absolute;left:1200px; ">
          <a class="nav-link ps-5 text-danger " style="font-size:20px;" href="{% url 'account:user_logout' %}">Logout</a>
        </li>

          {% else %}
          <li class="nav-item">
          <a class="nav-link ps-5" href="{% url 'account:register' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link ps-5" href="{% url 'account:login' %}">Login</a>
        </li>
          {% endif %}

<!--        <li class="nav-item dropdown">-->
<!--          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">-->
<!--            More-->
<!--          </a>-->
<!--          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--            <li><a class="dropdown-item" href="#">Action</a></li>-->
<!--            <li><a class="dropdown-item" href="#">Another action</a></li>-->
<!--            <li><hr class="dropdown-divider"></li>-->
<!--            <li><a class="dropdown-item" href="#">Something else here</a></li>-->
<!--          </ul>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
<!--        </li>-->
<!--      </ul>-->
<!--      <form class="d-flex">-->
<!--        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
<!--        <button class="btn btn-outline-danger" type="submit">Search</button>-->
<!--      </form>-->
    </div>
  </div>
</nav>

{%block content %}       <!-- just declared here used to add different content in different pages-->
{%endblock%}

<br> <br>
<div class="footer">    <!-- used to inherit this div to other pages which loads this templates  -->

</div>
</body>
</html>

templates/create.html
<!DOCTYPE html>
{% extends "base.html" %}        <!--  this loads the base.html template to this page  -->
{% load static %}              <!--always add load static after extends page---->
{% block title%}
home
{% endblock %}
{% block content %}

<div class="container">

<form method="POST" enctype="multipart/form-data">             <!-- in applic level form add method="POST" to send this form content to server -->
                   <!--here enctype is for media content,uploading type sending , updating and all-->

 {% csrf_token %}         <!--security feature used to send encrypted data from client side without getting manipulated  -->
    <div class="mb-3">
  <label  class="form-label">Account Number</label>
  <input type="number" class="form-control" name="an"  placeholder="Enter Title">
</div>                   <!--for each input type add name="t" used to retrieve value   -->

    <div class="mb-3">
  <label  class="form-label">Account Holder Name</label>
  <input type="text" class="form-control" name="hn"  placeholder="Enter Author">
</div>                                 <!--for each input type add name="t" used to retrieve value   -->

    <div class="mb-3">
  <label class="form-label">Account Type</label>
  <input type="text" class="form-control" name="at"  placeholder="Enter Price">
</div>                       <!--for each input type add name="t" used to retrieve value   -->

    <div class="mb-3">
  <label class="form-label">Balance</label>
  <input type="number" class="form-control" name="b"  placeholder="Enter Price">
</div>

<!-- <div class="mb-3">-->
<!--  <label class="form-label">Cover</label>-->
<!--  <input type="file" class="form-control" name="cv" >-->
<!--</div>-->

<!--     <div class="mb-3">-->
<!--  <label class="form-label">Pdf</label>-->
<!--  <input type="file" class="form-control" name="pd"  >-->
<!--</div>-->


       <div class="mb-3">
    <center>
    <input type="submit"  class="btn btn-danger"></center>
    </div>

 </form>

{% endblock %}

templates/home.html
<!DOCTYPE html>
{% extends "base.html" %}        <!--  this loads the base.html template to this page  -->
{% load static %}              <!--always add load static after extends page---->
{% block title%}
home
{% endblock %}
{% block content %}
<br>
<center>

    {% if user.is_authenticated %}          <!--here if user login or when user is login succesfully so enters into if-->
    <h1 class="text-center text-dark">Welcome <span style="text:red;">{{user.username}}</span></h1>      <!-- that login user username is shown here -->
    {% else %}
    <h1 class="text-center text-dark">Welcome</h1>
    {% endif %}
<br> <br>
    <img src="{% static 'image/bank7.jpeg' %}" height="500px" width="100%">
</center>

<br> <br>
<h3 style="text-align:center">About Us</h3>
<br>
    <p>Soohan Bank of India (SBI) a Fortune 500 company, is an Indian Multinational, Public Sector Banking and Financial services statutory body headquartered in Mumbai. The rich heritage and legacy of over 200 years, accredits SBI as the most trusted Bank by Indians through generations.

SBI, the largest Indian Bank with 1/4th market share, serves over 50 crore customers through its vast network of over 22,405 branches, 65,627 ATMs/ADWMs, 76,089 BC outlets, with an undeterred focus on innovation, and customer centricity, which stems from the core values of the Bank - Service, Transparency, Ethics, Politeness and Sustainability.

The Bank has successfully diversified businesses through its various subsidiaries i.e SBI General Insurance, SBI Life Insurance, SBI Mutual Fund, SBI Card, etc. It has spread its presence globally and operates across time zones through 235 offices in 29 foreign countries.

Growing with times, SBI continues to redefine banking in India, as it aims to offer responsible and sustainable Banking solutions..</p>

{% endblock %}

templates/login.html
<!DOCTYPE html>
{% extends "base.html" %}        <!--  this loads the base.html template to this page  -->
{% load static %}
{% block title%}
login
{% endblock %}

{% block content %}

<div class="container">

<form method="POST">             <!-- in applic level form add method="POST" to send this form content to server -->
                   <!--here enctype is for media content,uploading type sending , updating and all-->

 {% csrf_token %}         <!--security feature used to send encrypted data from client side without getting manipulated  -->
    <div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u"  placeholder="Enter Username">
</div>                   <!--for each input type add name="t" used to retrieve value   -->

    <div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p"  placeholder="Enter Password">
</div>                                 <!--for each input type add name="t" used to retrieve value   -->


       <div class="mb-3">
    <center>
    <input type="submit"  class="btn btn-danger"></center>
    </div>

 </form>


{% endblock %}


<!--               for template inheritance we just need the content that we want only in this page-------------------- -->

templates/register.html
<!DOCTYPE html>
{% extends "base.html" %}        <!--  this loads the base.html template to this page  -->
{% load static %}
{% block title%}
register
{% endblock %}
{% block content %}

<div class="container">

<form method="POST">             <!-- in applic level form add method="POST" to send this form content to server -->
                   <!--here enctype is for media content,uploading type sending , updating and all-->

 {% csrf_token %}         <!--security feature used to send encrypted data from client side without getting manipulated  -->
    <div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u"  placeholder="Enter Username">
</div>                   <!--for each input type add name="t" used to retrieve value   -->

    <div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p"  placeholder="Enter Password">
</div>                                 <!--for each input type add name="t" used to retrieve value   -->

    <div class="mb-3">
  <label class="form-label">Confirm Password</label>
  <input type="password" class="form-control" name="cp"  placeholder="Re-Enter Password">
</div>                       <!--for each input type add name="t" used to retrieve value   -->

 <div class="mb-3">
  <label class="form-label">Email</label>
  <input type="text" class="form-control" name="e" placeholder="Enter Email">
</div>

    <div class="mb-3">
  <label class="form-label">First name</label>
  <input type="text" class="form-control" name="fn" placeholder="Enter First name">
</div>

    <div class="mb-3">
  <label class="form-label">Last name</label>
  <input type="text" class="form-control" name="ln" placeholder="Enter Last name">
</div>


       <div class="mb-3">
    <center>
    <input type="submit"  class="btn btn-danger"></center>
    </div>

 </form>

{% endblock %}

templates/update.html
<!DOCTYPE html>
{% extends "base.html" %}        <!--  this loads the base.html template to this page  -->
{% load static %}
               <!--need to declare here before use crispy forms --->
{% block title%}
add1
{% endblock %}

{% block content %}
                             <!--creating form through builtin--------------------------------------------->

<h2>Update Account</h2>
                       <!--{# {{form}} #} is data send from view its an object of class form  ---->
<form method="POST" enctype="multipart/form-data">
     <!--here enctype is for media content,uploading type sending , updating and all-->


    {% csrf_token %}

     {{form}}
    <input type="submit">
</form>


 {% endblock %}

templates/update2.html
<!DOCTYPE html>
{% extends "base.html" %}        <!--  this loads the base.html template to this page  -->
{% load static %}              <!--always add load static after extends page---->
{% block title%}
home
{% endblock %}
{% block content %}


<table class="table table-bordered" style="">

    {% for i in a %}
    <tr>
        <th>Account Number : </th>                   <!-- here id is passed as context in jinja2 form (b) then that b is taken to show value b.name  -->
        <td>{{i.account_number}}</td>
    </tr>
    <tr>
        <th>Account Number : </th>                   <!-- here id is passed as context in jinja2 form (b) then that b is taken to show value b.name  -->
        <td>{{i.account_holder_name}}</td>
    </tr>
    <tr>
        <th>Account Number : </th>                   <!-- here id is passed as context in jinja2 form (b) then that b is taken to show value b.name  -->
        <td>{{i.account_type}}</td>
    </tr>
    <tr>
        <th>Account Number : </th>                   <!-- here id is passed as context in jinja2 form (b) then that b is taken to show value b.name  -->
        <td>{{i.balance}}</td>
    </tr>
    <tr>
        <th>Account Number : </th>                   <!-- here id is passed as context in jinja2 form (b) then that b is taken to show value b.name  -->
        <td>{{i.user}}</td>
    </tr>

        <a href="{% url 'account:edit' i.id %}" class="btn btn-primary">Update Acccount</a>
            <a href="{% url 'account:delete' i.id %}" class="btn btn-primary">Delete Acccount</a>




    {% endfor %}

</table>


{% endblock %}

templates/viewtransaction.html
<!DOCTYPE html>
{% extends "base.html" %}        <!--  this loads the base.html template to this page  -->
{% load static %}              <!--always add load static after extends page---->
{% block title%}
home
{% endblock %}
{% block content %}


<table class="table table-bordered" style="">

    {% for i in t %}
    <tr>
        <th>Account Number : </th>                   <!-- here id is passed as context in jinja2 form (b) then that b is taken to show value b.name  -->
        <td>{{i.account.account_number}}</td>
    </tr>

     <tr>
        <th>Customer Name : </th>                   <!-- here id is passed as context in jinja2 form (b) then that b is taken to show value b.name  -->
        <td>{{i.account.account_holder_name}}</td>
    </tr>
     <tr>
        <th>Amount : </th>                   <!-- here id is passed as context in jinja2 form (b) then that b is taken to show value b.name  -->
        <td>{{i.amount}}</td>
    </tr>
     <tr>
        <th>Balance : </th>                   <!-- here id is passed as context in jinja2 form (b) then that b is taken to show value b.name  -->
        <td>{{i.account.balance}}</td>
    </tr>
    <tr>
        <th>Date : </th>                   <!-- here id is passed as context in jinja2 form (b) then that b is taken to show value b.name  -->
        <td>{{i.date}}</td>
    </tr>
    {% endfor %}

</table>


{% endblock %}